### ISSUE TITLE
Feedback Request:asymmetric

### ISSUE THREAD

**Issue by Tanujadubba** [Techgrounds-Cloud-9/cloud-9-Tanujadubba#7]
**Feedback Request [SUBJECT]**
Permalink to file: [https://github.com/Techgrounds-Cloud-9/cloud-9-Tanujadubba/blob/main/01_Fundamentals_1/week3/sec-05asymmetric.md]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by katelindt** [comment]
**Summary**
- Does the summary describe the subject matter fully?
yes
- Is the summary written in own words?
It's copied from one of the sources, but a very accurate and good description was chosen.
- Is there crucial information missing in the summary? 
no
- Is the description clear enough?
yes

**Key Terminology**
- Are there missing key terms?
I would advise you to add information about rsa and also a little more about private & public key.
- Are the key terms explained well?
yes
**Sources**
- Are the sources mentioned?
yes
- Are the mentioned sources correct?
yes
**Excercise**
(Where applicable)
- Is the result correct?
yes, but I would also add screenshots of the encryption process.
- Are the experienced problems and solutions described well?
- yes
